#!/bin/bash
set -euo pipefail

this_dir=$(cd $(dirname $0); pwd -P)
repo_dir=$(dirname $this_dir)
samples_dir=$repo_dir/samples

cd $repo_dir
#stack exec ghcid -- -T":main -p $samples_dir/project.yaml -a $samples_dir/availability.yaml -s 2018-10-30"
stack exec ghcid -- -T":main"
